using System.Text;

namespace XUnityToolkit_WebUI.Services;

internal static class PreTranslationRegexFormat
{
    internal const string BaseSection = "base";
    internal const string CustomSection = "custom";
    internal const string DynamicSection = "dynamic";

    private const string ManagedHeader = "// XUnity Toolkit managed pre-translation regex file";
    private const string ManagedNote = "// Base and dynamic sections may be regenerated by pre-translation.";
    private const string SectionMarkerPrefix = "// XUT_SECTION:";

    internal static ParsedPreTranslationRegexFile Parse(string? content)
    {
        if (string.IsNullOrWhiteSpace(content))
            return new ParsedPreTranslationRegexFile([]);

        var lines = SplitLines(content);
        return lines.Any(static line => line.TrimStart().StartsWith(SectionMarkerPrefix, StringComparison.Ordinal))
            ? ParseManaged(lines)
            : ParseLegacy(lines);
    }

    internal static List<PreTranslationRegexRule> ParseRulesStrict(string content, string defaultSection = CustomSection)
        => ParseLoose(content, defaultSection, strict: true);

    internal static List<PreTranslationRegexRule> ParseLooseRules(string? content, string defaultSection = CustomSection)
        => ParseLoose(content, defaultSection, strict: false);

    internal static IReadOnlyList<PreTranslationRegexRule> CreateBaseRules()
    {
        return
        [
            CreateRule(BaseSection, "sr", @"^([\S\s]+?)\n([\S\s]+)$", "$1\\n$2", 0),
            CreateRule(BaseSection, "sr", @"^([\S\s]+?)\n([\S\s]+?)\n([\S\s]+)$", "$1\\n$2\\n$3", 1),
        ];
    }

    internal static IReadOnlyList<PreTranslationRegexRule> CreateDynamicRules(
        IEnumerable<(string Pattern, string Replacement)> entries)
    {
        return entries
            .Select((entry, index) => CreateRule(DynamicSection, "r", entry.Pattern, entry.Replacement, index))
            .ToList();
    }

    internal static string SerializeManaged(IEnumerable<PreTranslationRegexRule> rules)
    {
        var grouped = GroupBySection(rules);
        var sb = new StringBuilder();
        sb.AppendLine(ManagedHeader);
        sb.AppendLine(ManagedNote);
        AppendSection(sb, BaseSection, grouped[BaseSection]);
        AppendSection(sb, CustomSection, grouped[CustomSection]);
        AppendSection(sb, DynamicSection, grouped[DynamicSection]);
        return sb.ToString();
    }

    internal static string SerializeRules(IEnumerable<PreTranslationRegexRule> rules)
    {
        var sb = new StringBuilder();
        foreach (var rule in rules)
            sb.AppendLine(SerializeRuleLine(rule));
        return sb.ToString();
    }

    internal static string RebuildManagedFile(
        string? existingContent,
        bool includeBaseRules,
        IEnumerable<PreTranslationRegexRule> dynamicRules,
        string? legacyCustomContent = null)
    {
        var parsed = Parse(existingContent);
        var customRules = parsed.Rules
            .Where(static rule => string.Equals(rule.Section, CustomSection, StringComparison.Ordinal))
            .ToList();

        if (customRules.Count == 0 && !string.IsNullOrWhiteSpace(legacyCustomContent))
            customRules = ParseLooseRules(legacyCustomContent, CustomSection);

        var merged = new List<PreTranslationRegexRule>();
        if (includeBaseRules)
            merged.AddRange(CreateBaseRules());
        merged.AddRange(ReindexSection(customRules, CustomSection));
        merged.AddRange(ReindexSection(dynamicRules, DynamicSection));

        return SerializeManaged(merged);
    }

    internal static string ExtractCustomContent(string? content)
    {
        var parsed = Parse(content);
        return SerializeRules(parsed.Rules.Where(static rule =>
            string.Equals(rule.Section, CustomSection, StringComparison.Ordinal)));
    }

    private static ParsedPreTranslationRegexFile ParseManaged(IReadOnlyList<string> lines)
    {
        var rules = new List<PreTranslationRegexRule>();
        var section = CustomSection;
        var sectionCounters = new Dictionary<string, int>(StringComparer.Ordinal)
        {
            [BaseSection] = 0,
            [CustomSection] = 0,
            [DynamicSection] = 0,
        };

        foreach (var rawLine in lines)
        {
            var trimmed = rawLine.Trim();
            if (TryReadSectionMarker(trimmed, out var nextSection))
            {
                section = nextSection;
                continue;
            }

            if (TryParseRuleLine(trimmed, section, sectionCounters[section], out var rule))
            {
                sectionCounters[section]++;
                rules.Add(rule);
            }
        }

        return new ParsedPreTranslationRegexFile(rules);
    }

    private static ParsedPreTranslationRegexFile ParseLegacy(IReadOnlyList<string> lines)
    {
        var rules = new List<PreTranslationRegexRule>();
        var section = BaseSection;
        var sectionCounters = new Dictionary<string, int>(StringComparer.Ordinal)
        {
            [BaseSection] = 0,
            [CustomSection] = 0,
            [DynamicSection] = 0,
        };

        foreach (var rawLine in lines)
        {
            var trimmed = rawLine.Trim();
            if (string.IsNullOrWhiteSpace(trimmed))
                continue;

            if (trimmed.StartsWith("//", StringComparison.Ordinal))
            {
                if (trimmed.Contains("Custom patterns", StringComparison.OrdinalIgnoreCase))
                    section = CustomSection;
                else if (trimmed.Contains("Dynamic template variable patterns", StringComparison.OrdinalIgnoreCase))
                    section = DynamicSection;
                else if (trimmed.Contains("Two-line concatenation", StringComparison.OrdinalIgnoreCase)
                    || trimmed.Contains("Three-line concatenation", StringComparison.OrdinalIgnoreCase))
                    section = BaseSection;

                continue;
            }

            if (TryParseRuleLine(trimmed, section, sectionCounters[section], out var rule))
            {
                sectionCounters[section]++;
                rules.Add(rule);
            }
        }

        return new ParsedPreTranslationRegexFile(rules);
    }

    private static List<PreTranslationRegexRule> ParseLoose(string? content, string defaultSection, bool strict)
    {
        var normalizedSection = NormalizeSection(defaultSection);
        var rules = new List<PreTranslationRegexRule>();
        if (string.IsNullOrWhiteSpace(content))
            return rules;

        var index = 0;
        foreach (var rawLine in SplitLines(content))
        {
            var trimmed = rawLine.Trim();
            if (string.IsNullOrWhiteSpace(trimmed) || trimmed.StartsWith("//", StringComparison.Ordinal))
                continue;

            if (!TryParseRuleLine(trimmed, normalizedSection, index, out var rule))
            {
                if (strict)
                    throw new FormatException($"Invalid regex rule line: {trimmed}");
                continue;
            }

            rules.Add(rule);
            index++;
        }

        return rules;
    }

    private static Dictionary<string, List<PreTranslationRegexRule>> GroupBySection(IEnumerable<PreTranslationRegexRule> rules)
    {
        var grouped = new Dictionary<string, List<PreTranslationRegexRule>>(StringComparer.Ordinal)
        {
            [BaseSection] = [],
            [CustomSection] = [],
            [DynamicSection] = [],
        };

        foreach (var rule in rules)
        {
            var section = NormalizeSection(rule.Section);
            var kind = NormalizeKind(rule.Kind);
            grouped[section].Add(new PreTranslationRegexRule(
                Id: rule.Id,
                Section: section,
                Kind: kind,
                Pattern: rule.Pattern,
                Replacement: rule.Replacement));
        }

        return grouped;
    }

    private static void AppendSection(StringBuilder sb, string section, IReadOnlyList<PreTranslationRegexRule> rules)
    {
        sb.AppendLine();
        sb.AppendLine($"{SectionMarkerPrefix}{section}");
        foreach (var rule in ReindexSection(rules, section))
            sb.AppendLine(SerializeRuleLine(rule));
    }

    private static IEnumerable<PreTranslationRegexRule> ReindexSection(
        IEnumerable<PreTranslationRegexRule> rules,
        string section)
    {
        return rules.Select((rule, index) => CreateRule(
            NormalizeSection(section),
            NormalizeKind(rule.Kind),
            rule.Pattern,
            rule.Replacement,
            index));
    }

    private static string SerializeRuleLine(PreTranslationRegexRule rule)
    {
        return $"{NormalizeKind(rule.Kind)}:\"{EscapePattern(rule.Pattern)}\"={rule.Replacement}";
    }

    private static PreTranslationRegexRule CreateRule(
        string section,
        string kind,
        string pattern,
        string replacement,
        int index)
    {
        return new PreTranslationRegexRule(
            Id: $"{section}-{index}",
            Section: NormalizeSection(section),
            Kind: NormalizeKind(kind),
            Pattern: pattern,
            Replacement: replacement);
    }

    private static bool TryReadSectionMarker(string line, out string section)
    {
        if (line.StartsWith(SectionMarkerPrefix, StringComparison.Ordinal))
        {
            section = NormalizeSection(line[SectionMarkerPrefix.Length..].Trim());
            return true;
        }

        section = CustomSection;
        return false;
    }

    private static bool TryParseRuleLine(string line, string section, int index, out PreTranslationRegexRule rule)
    {
        rule = default!;
        if (string.IsNullOrWhiteSpace(line) || line.StartsWith("//", StringComparison.Ordinal))
            return false;

        var kind = line.StartsWith("sr:", StringComparison.Ordinal)
            ? "sr"
            : line.StartsWith("r:", StringComparison.Ordinal)
                ? "r"
                : string.Empty;
        if (kind.Length == 0)
            return false;

        var quoteStart = kind.Length + 1;
        if (quoteStart >= line.Length || line[quoteStart] != '"')
            return false;

        if (!TryReadPattern(line, quoteStart + 1, out var pattern, out var nextIndex))
            return false;
        if (nextIndex >= line.Length || line[nextIndex] != '=')
            return false;

        rule = CreateRule(section, kind, pattern, line[(nextIndex + 1)..], index);
        return true;
    }

    private static bool TryReadPattern(string input, int start, out string pattern, out int nextIndex)
    {
        var sb = new StringBuilder();
        for (var i = start; i < input.Length; i++)
        {
            var current = input[i];
            if (current == '"' && input[i - 1] != '\\')
            {
                pattern = sb.ToString();
                nextIndex = i + 1;
                return true;
            }

            if (current == '\\' && i + 1 < input.Length && input[i + 1] == '"')
            {
                sb.Append('"');
                i++;
                continue;
            }

            sb.Append(current);
        }

        pattern = string.Empty;
        nextIndex = input.Length;
        return false;
    }

    private static string EscapePattern(string pattern)
        => pattern.Replace("\"", "\\\"", StringComparison.Ordinal);

    private static string NormalizeSection(string section)
    {
        return section switch
        {
            BaseSection => BaseSection,
            CustomSection => CustomSection,
            DynamicSection => DynamicSection,
            _ => throw new FormatException($"Unsupported regex rule section: {section}"),
        };
    }

    private static string NormalizeKind(string kind)
    {
        return kind switch
        {
            "sr" => "sr",
            "r" => "r",
            _ => throw new FormatException($"Unsupported regex rule kind: {kind}"),
        };
    }

    private static List<string> SplitLines(string content)
    {
        return content
            .Split(["\r\n", "\n", "\r"], StringSplitOptions.None)
            .ToList();
    }
}

internal sealed record PreTranslationRegexRule(
    string Id,
    string Section,
    string Kind,
    string Pattern,
    string Replacement);

internal sealed record ParsedPreTranslationRegexFile(
    IReadOnlyList<PreTranslationRegexRule> Rules);
