namespace XUnityToolkit_WebUI.Services;

internal static class TranslationEditorPathResolver
{
    internal static string ResolveDefaultTranslationFilePath(string gamePath, string? outputFile, string targetLang)
    {
        var template = string.IsNullOrWhiteSpace(outputFile)
            ? @"Translation\{Lang}\Text\_AutoGeneratedTranslations.txt"
            : outputFile;
        var relative = template.Replace("{Lang}", targetLang, StringComparison.Ordinal);
        return ResolvePathUnderBepInEx(gamePath, relative);
    }

    private static string ResolvePathUnderBepInEx(string gamePath, string relativePath)
    {
        var fullPath = Path.GetFullPath(Path.Combine(gamePath, "BepInEx", relativePath));
        var allowedBase = Path.GetFullPath(Path.Combine(gamePath, "BepInEx")) + Path.DirectorySeparatorChar;
        if (!fullPath.StartsWith(allowedBase, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("Translation file path escapes game directory.");
        return fullPath;
    }
}
