/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiTranslationCard: typeof import('./components/settings/AiTranslationCard.vue')['default']
    AppShell: typeof import('./components/layout/AppShell.vue')['default']
    BackgroundPickerModal: typeof import('./components/library/BackgroundPickerModal.vue')['default']
    ConfigPanel: typeof import('./components/config/ConfigPanel.vue')['default']
    CoverPickerModal: typeof import('./components/library/CoverPickerModal.vue')['default']
    FileExplorerModal: typeof import('./components/common/FileExplorerModal.vue')['default']
    GameCard: typeof import('./components/library/GameCard.vue')['default']
    IconPickerModal: typeof import('./components/library/IconPickerModal.vue')['default']
    InstallProgressDrawer: typeof import('./components/progress/InstallProgressDrawer.vue')['default']
    LibraryCustomizer: typeof import('./components/library/LibraryCustomizer.vue')['default']
    LocalAiPanel: typeof import('./components/settings/LocalAiPanel.vue')['default']
    NSelect: typeof import('naive-ui')['NSelect']
    PluginHealthCard: typeof import('./components/health/PluginHealthCard.vue')['default']
    RegexRuleEditor: typeof import('./components/translation/RegexRuleEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebImageSearchTab: typeof import('./components/library/WebImageSearchTab.vue')['default']
  }
}
